'use strict';

export default [
	'/:userslug/collection/:collection/tags/:tags/search/:search/items/:items',
	'/:userslug/collection/:collection/tags/:tags/search/:search/items/:items',
	'/:userslug/collection/:collection/tags/:tags/items/:items',
	'/:userslug/collection/:collection/search/:search/items/:items',
	'/:userslug/collection/:collection/items/:items',
	'/:userslug/collection/:collection/tags/:tags/search/:search',
	'/:userslug/collection/:collection/tags/:tags/',
	'/:userslug/collection/:collection/search/:search',
	'/:userslug/collection/:collection/:view(libraries|library|collection|item-list|item-details)?',
	'/:userslug/items/:items',
	'/:userslug/tags/:tags/search/:search/items/:items',
	'/:userslug/tags/:tags/search/:search',
	'/:userslug/tags/:tags/items/:items',
	'/:userslug/tags/:tags',
	'/:userslug/search/:search/items/:items',
	'/:userslug/search/:search',
	'/:userslug/trash/items/:items',
	'/:userslug/trash',
	'/:userslug/publications/items/:items',
	'/:userslug/publications',
	'/:userslug/:view(library|collection|item-list|item-details)',

	'/groups/:groupid/:groupslug/collection/:collection/tags/:tags/search/:search/items/:items',
	'/groups/:groupid/:groupslug/collection/:collection/tags/:tags/search/:search/items/:items',
	'/groups/:groupid/:groupslug/collection/:collection/tags/:tags/items/:items',
	'/groups/:groupid/:groupslug/collection/:collection/search/:search/items/:items',
	'/groups/:groupid/:groupslug/collection/:collection/items/:items',
	'/groups/:groupid/:groupslug/collection/:collection/tags/:tags/search/:search',
	'/groups/:groupid/:groupslug/collection/:collection/tags/:tags/',
	'/groups/:groupid/:groupslug/collection/:collection/search/:search',
	'/groups/:groupid/:groupslug/collection/:collection/:view(libraries|library|collection|item-list|item-details)?',
	'/groups/:groupid/:groupslug/items/:items',
	'/groups/:groupid/:groupslug/tags/:tags/search/:search/items/:items',
	'/groups/:groupid/:groupslug/tags/:tags/search/:search',
	'/groups/:groupid/:groupslug/tags/:tags/items/:items',
	'/groups/:groupid/:groupslug/tags/:tags',
	'/groups/:groupid/:groupslug/search/:search/items/:items',
	'/groups/:groupid/:groupslug/search/:search',
	'/groups/:groupid/:groupslug/trash/items/:items',
	'/groups/:groupid/:groupslug/trash',
	'/groups/:groupid/:groupslug/publications/items/:items',
	'/groups/:groupid/:groupslug/publications',
	'/groups/:groupid/:groupslug/:view(library|collection|item-list|item-details)',
	'/:view(libraries)',
];
