'use strict';

export const routes = [
	'/:userslug/collection/:collection/tags/:tags/search/:search/items/:items',
	'/:userslug/collection/:collection/tags/:tags/search/:search/items/:items',
	'/:userslug/collection/:collection/tags/:tags/items/:items',
	'/:userslug/collection/:collection/search/:search/items/:items',
	'/:userslug/collection/:collection/items/:items',
	'/:userslug/collection/:collection/tags/:tags/search/:search',
	'/:userslug/collection/:collection/tags/:tags/',
	'/:userslug/collection/:collection/search/:search',
	'/:userslug/collection/:collection/:view(libraries|library|collection|item-list|item-details)?',
	'/:userslug/items/:items',
	'/:userslug/tags/:tags/search/:search/items/:items',
	'/:userslug/tags/:tags/search/:search',
	'/:userslug/tags/:tags/items/:items',
	'/:userslug/tags/:tags',
	'/:userslug/search/:search/items/:items',
	'/:userslug/search/:search',
	'/:userslug/trash/search/:search/items/:items',
	'/:userslug/trash/items/:items',
	'/:userslug/trash/search/:search',
	'/:userslug/trash',
	'/:userslug/publications/search/:search/items/:items',
	'/:userslug/publications/items/:items',
	'/:userslug/publications/search/:search',
	'/:userslug/publications',
	'/:userslug/:view(library|collection|item-list|item-details)',

	'/groups/:groupid/:groupslug/collection/:collection/tags/:tags/search/:search/items/:items',
	'/groups/:groupid/:groupslug/collection/:collection/tags/:tags/search/:search/items/:items',
	'/groups/:groupid/:groupslug/collection/:collection/tags/:tags/items/:items',
	'/groups/:groupid/:groupslug/collection/:collection/search/:search/items/:items',
	'/groups/:groupid/:groupslug/collection/:collection/items/:items',
	'/groups/:groupid/:groupslug/collection/:collection/tags/:tags/search/:search',
	'/groups/:groupid/:groupslug/collection/:collection/tags/:tags/',
	'/groups/:groupid/:groupslug/collection/:collection/search/:search',
	'/groups/:groupid/:groupslug/collection/:collection/:view(libraries|library|collection|item-list|item-details)?',
	'/groups/:groupid/:groupslug/items/:items',
	'/groups/:groupid/:groupslug/tags/:tags/search/:search/items/:items',
	'/groups/:groupid/:groupslug/tags/:tags/search/:search',
	'/groups/:groupid/:groupslug/tags/:tags/items/:items',
	'/groups/:groupid/:groupslug/tags/:tags',
	'/groups/:groupid/:groupslug/search/:search/items/:items',
	'/groups/:groupid/:groupslug/search/:search',
	'/groups/:groupid/:groupslug/trash/search/:search/items/:items',
	'/groups/:groupid/:groupslug/trash/items/:items',
	'/groups/:groupid/:groupslug/trash/search/:search',
	'/groups/:groupid/:groupslug/trash',
	'/groups/:groupid/:groupslug/publications/search/:search/items/:items',
	'/groups/:groupid/:groupslug/publications/items/:items',
	'/groups/:groupid/:groupslug/publications/search/:search',
	'/groups/:groupid/:groupslug/publications',
	'/groups/:groupid/:groupslug/:view(library|collection|item-list|item-details)',
	'/:view(libraries)',
]

export const redirects = [
	{ 	from: '/:userslug/items/collectionKey/trash/itemKey/:items/:optional?/:mode?',
		to: '/:userslug/trash/items/:items' },
	{ 	from: '/:userslug/items/collectionKey/:collection/itemKey/:items/:optional?/:mode?',
		to: '/:userslug/collection/:collection/items/:items' },
	{	from: '/:userslug/items/collectionKey/trash/q/:search',
		to: '/:userslug/trash/search/:search' },
	{	from: '/:userslug/items/collectionKey/trash/:optional?/:mode?',
		to: '/:userslug/trash' },
	{	from: '/:userslug/items/collectionKey/:collection/q/:search/:optional?/:mode?',
		to: '/:userslug/collection/:collection/search/:search' },
	{	from: '/:userslug/items/collectionKey/:collection/:optional?/:mode?',
		to: '/:userslug/collection/:collection' },
	{ 	from: '/:userslug/items/action/newItem/collectionKey/trash/:optional?/:mode?',
		to: '/:userslug/trash' },
	{ 	from: '/:userslug/items/action/newItem/collectionKey/:collection/:optional?/:mode?',
		to: '/:userslug/collection/:collection' },
	{ 	from: '/:userslug/items/itemKey/:items/:optional?/:mode?',
		to: '/:userslug/items/:items' },
	{ 	from: '/:userslug/items/action/newItem/:optional?/:mode?',
		to: '/:userslug/library' },
	{ 	from: '/:userslug/items/q/:search',
		to: '/:userslug/search/:search' },
	{ 	from: '/:userslug/items',
		to: '/:userslug/library' },

	{ 	from: '/groups/:groupid/:groupslug/items/collectionKey/trash/itemKey/:items/:optional?/:mode?',
		to: '/groups/:groupid/:groupslug/trash/items/:items' },
	{ 	from: '/groups/:groupid/:groupslug/items/collectionKey/:collection/itemKey/:items/:optional?/:mode?',
		to: '/groups/:groupid/:groupslug/collection/:collection/items/:items' },
	{	from: '/groups/:groupid/:groupslug/items/collectionKey/trash/q/:search',
		to: '/groups/:groupid/:groupslug/trash/search/:search' },
	{	from: '/groups/:groupid/:groupslug/items/collectionKey/trash/:optional?/:mode?',
		to: '/groups/:groupid/:groupslug/trash' },
	{	from: '/groups/:groupid/:groupslug/items/collectionKey/:collection/q/:search/:optional?/:mode?',
		to: '/groups/:groupid/:groupslug/collection/:collection/search/:search' },
	{	from: '/groups/:groupid/:groupslug/items/collectionKey/:collection/:optional?/:mode?',
		to: '/groups/:groupid/:groupslug/collection/:collection' },
	{ 	from: '/groups/:groupid/:groupslug/items/action/newItem/collectionKey/trash/:optional?/:mode?',
		to: '/groups/:groupid/:groupslug/trash' },
	{ 	from: '/groups/:groupid/:groupslug/items/action/newItem/collectionKey/:collection/:optional?/:mode?',
		to: '/groups/:groupid/:groupslug/collection/:collection' },
	{ 	from: '/groups/:groupid/:groupslug/items/itemKey/:items/:optional?/:mode?',
		to: '/groups/:groupid/:groupslug/items/:items' },
	{ 	from: '/groups/:groupid/:groupslug/items/action/newItem/:optional?/:mode?',
		to: '/groups/:groupid/:groupslug/library' },
	{ 	from: '/groups/:groupid/:groupslug/items/q/:search',
		to: '/groups/:groupid/:groupslug/search/:search' },
	{ 	from: '/groups/:groupid/:groupslug/items',
		to: '/groups/:groupid/:groupslug/library' },

	{	from: '/groups/:groupid/:groupslug',
		to: '/groups/:groupid/:groupslug/library' },

	{ 	from: '/',
		to: '/libraries' },
];
