export default [
	{ label: 'BibLaTeX', extension: 'bib', key: 'biblatex' },
	{ label: 'Bibliographic Ontology RDF', extension: 'rdf', key: 'rdf_bibliontology' },
	{ label: 'BibTeX', extension: 'bib', key: 'bibtex' },
	{ label: 'COinS', extension: null, key: 'coins' },
	{ label: 'CSL-JSON', extension: 'json', key: 'csljson' },
	{ label: 'CSV', extension: 'csv', key: 'csv' },
	{ label: 'EndNote XML', extension: 'xml', key: 'endnote_xml' },
	{ label: 'MODS', extension: 'xml', key: 'mods' },
	{ label: 'Netscape Bookmark File Format', extension: 'html', key: 'bookmarks' },
	{ label: 'Refer/BibIX', extension: 'txt', key: 'refer' },
	{ label: 'RefWorks Tagged', extension: 'txt', key: 'refworks_tagged' },
	{ label: 'RIS', extension: 'ris', key: 'ris' },
	{ label: 'Text Encoding Initiative (TEI)', extension: 'xml', key: 'tei' },
	{ label: 'Unqualified Dublin Core RDF', extension: 'rdf', key: 'rdf_dc' },
	{ label: 'Wikipedia Citation Templates', extension: 'txt', key: 'wikipedia' },
	{ label: 'Zotero RDF', extension: 'rdf', key: 'rdf_zotero' },
];
