// TODO: localize
export const locators = {
    act: 'Act',
    appendix: 'Appendix',
    'article-locator': 'Article Locator',
    book: 'Book',
    canon: 'Canon',
    chapter: 'Chapter',
    column: 'Column',
    elocation: 'eLocation',
    equation: 'Equation',
    figure: 'Figure',
    folio: 'Folio',
    issue: 'Issue',
    line: 'Line',
    note: 'Note',
    opus: 'Opus',
    page: 'Page',
    paragraph: 'Paragraph',
    part: 'Part',
    rule: 'Rule',
    scene: 'Scene',
    section: 'Section',
    'sub verbo': 'Sub Verbo',
    'sub-verbo': 'Sub Verbo',
    table: 'Table',
    timestamp: 'Timestamp',
    'title-locator': 'Title Locator',
    verse: 'Verse',
    volume: 'Volume'
};

export const locatorShortForms = {
    act: 'Act',
    appendix: 'app.',
    'article-locator': 'art.',
    book: 'bk.',
    canon: 'c.',
    chapter: 'chap.',
    column: 'col.',
    elocation: 'loc.',
    equation: 'eq.',
    figure: 'fig.',
    folio: 'fol.',
    issue: 'no.',
    line: 'l.',
    note: 'n.',
    opus: 'op.',
    page: 'p.',
    paragraph: 'para.',
    part: 'pt.',
    rule: 'r.',
    scene: 'sc.',
    section: 'sec.',
    'sub verbo': 's.v.',
    'sub-verbo': 's.v.',
    table: 'tbl.',
    timestamp: 'Timestamp',
    'title-locator': 'tit.',
    verse: 'v.',
    volume: 'vol.'
};
