'use strict';

module.exports = {
	'BIBLIOGRAPHY': 'BIBLIOGRAPHY',
	'COLLECTION_ADD': 'COLLECTION_ADD',
	'COLLECTION_RENAME': 'COLLECTION_RENAME',
	'COLLECTION_SELECT': 'COLLECTION_SELECT',
	'NEW_ITEM': 'NEW_ITEM',
};
