export const PICKS_SINGLE_ITEM = 'PICKER_PICKS_SINGLE_ITEM';
export const PICKS_MULTIPLE_ITEMS = 'PICKER_PICKS_ITEMS';
export const PICKS_SINGLE_COLLECTION = 'PICKER_PICKS_SINGLE_COLLECTION';
export const PICKS_MULTIPLE_COLLECTIONS = 'PICKER_PICKS_COLLECTIONS';
