// @TODO: Once we have localization, these will need to become part of localization

export const strings = {
	'general.red': 'Red',
	'general.orange': 'Orange',
	'general.yellow': 'Yellow',
	'general.green': 'Green',
	'general.blue': 'Blue',
	'general.purple': 'Purple',
	'general.magenta': 'Magenta',
	'general.gray': 'Gray',
	'general.copy': 'Copy',
	'general.delete': 'Delete',
	'general.clearSelection': 'Clear Selection',
	'general.back': 'Back',
	'general.update': 'Update',
	'general.cancel': 'Cancel',
	'general.print': 'Print',
	'pdfReader.firstPage': "First Page",
	'pdfReader.lastPage': "Last Page",
	'pdfReader.back': "Back",
	'pdfReader.forward': "Forward",
	'pdfReader.handTool': "Hand Tool",
	'pdfReader.verticalScrolling': "Vertical Scrolling",
	'pdfReader.horizontalScrolling': "Horizontal Scrolling",
	'pdfReader.wrappedScrolling': "Wrapped Scrolling",
	'pdfReader.noSpreads': "No Spreads",
	'pdfReader.oddSpreads': "Odd Spreads",
	'pdfReader.evenSpreads': "Even Spreads",
	'pdfReader.scrolled': "Scrolled",
	'pdfReader.paginated': "Paginated",
	'pdfReader.zoomIn': "Zoom In",
	'pdfReader.zoomOut': "Zoom Out",
	'pdfReader.zoomReset': "Reset Zoom",
	'pdfReader.zoomAuto': "Automatically Resize",
	'pdfReader.zoomPageWidth': "Zoom to Page Width",
	'pdfReader.zoomPageHeight': "Zoom to Page Height",
	'pdfReader.splitVertically': "Split Vertically",
	'pdfReader.splitHorizontally': "Split Horizontally",
	'pdfReader.transferFromPDF': "Import Annotations…",
	'pdfReader.rotatePageLeft': "Rotate Page Left",
	'pdfReader.rotatePageRight': "Rotate Page Right",
	'pdfReader.annotations': 'Annotations',
	'pdfReader.showAnnotations': 'Show Annotations',
	'pdfReader.searchAnnotations': 'Search Annotations',
	'pdfReader.noAnnotations': 'Create an annotation to see it in the sidebar',
	'pdfReader.noExtractedText': 'No extracted text',
	'pdfReader.addComment': 'Add comment',
	'pdfReader.addTags': 'Add tags…',
	'pdfReader.highlightText': 'Highlight Text',
	'pdfReader.underlineText': 'Underline Text',
	'pdfReader.addNote': 'Add Note',
	'pdfReader.addText': 'Add Text',
	'pdfReader.selectArea': 'Select Area',
	'pdfReader.draw': 'Draw',
	'pdfReader.erase': 'Erase',
	'pdfReader.pickColor': 'Pick a Color',
	'pdfReader.addToNote': 'Add to Note',
	'pdfReader.nextPage': 'Next Page',
	'pdfReader.previousPage': 'Previous Page',
	'pdfReader.page': 'Page',
	'pdfReader.location': 'Location',
	'pdfReader.readOnly': 'Read-only',
	'pdfReader.promptTransferFromPDF': 'Import Annotations',
	'pdfReader.promptTransferToPDF': 'Store Annotations in File',
	'pdfReader.promptPasswordProtected': 'The operation is not supported for password-protected PDF files.',
	'pdfReader.promptDeletePages': '= Delete Pages',
	'pdfReader.rotateLeft': 'Rotate Left',
	'pdfReader.rotateRight': 'Rotate Right',
	'pdfReader.editPageNumber': 'Edit Page Number…',
	'pdfReader.editAnnotationText': 'Edit Annotation Text',
	'pdfReader.copyImage': 'Copy Image',
	'pdfReader.saveImageAs': 'Save Image As…',
	'pdfReader.pageNumberPopupHeader': 'Change page number for:',
	'pdfReader.thisAnnotation': 'This annotation',
	'pdfReader.selectedAnnotations': 'Selected annotations',
	'pdfReader.thisPage': 'This page',
	'pdfReader.thisPageAndLaterPages': 'This page and later pages',
	'pdfReader.allPages': 'All pages',
	'pdfReader.autoDetect': 'Auto-Detect',
	'pdfReader.deleteAnnotation': 'Are you sure you want to delete the selected annotation?',
	'pdfReader.enterPassword': 'Enter the password to open this PDF file',
	'pdfReader.includeAnnotations': 'Include annotations',
	'pdfReader.preparingDocumentForPrinting': 'Preparing document for printing…',
	'pdfReader.phraseNotFound': 'Phrase not found',
	'pdfReader.deleteAnnotation.plural': 'Are you sure you want to delete the selected annotations?'
};
